// Generated by https://quicktype.io

export interface AnimeSearchInterface {
    pagination: Pagination;
    data: DatumSearch[];
  }
  
  export interface DatumSearch {
    mal_id: number;
    url: string;
    images: {[key: string]: Image};
    trailer: Trailer;
    approved: boolean;
    titles: Title[];
    title: string;
    title_english: string;
    title_japanese: string;
    title_synonyms: string[];
    type: string;
    source: string;
    episodes: number | null;
    status: string;
    airing: boolean;
    aired: Aired;
    duration: string;
    rating: string;
    score: number | null;
    scored_by: number | null;
    rank: number | null;
    popularity: number;
    members: number;
    favorites: number;
    synopsis: string;
    background: null;
    season: string;
    year: number;
    broadcast: Broadcast;
    producers: Genre[];
    licensors: any[];
    studios: Genre[];
    genres: Genre[];
    explicit_genres: any[];
    themes: Genre[];
    demographics: any[];
  }
  
  export interface Aired {
    from: string;
    to: null | string;
    prop: Prop;
    string: string;
  }
  
  export interface Prop {
    from: From;
    to: From;
  }
  
  export interface From {
    day: number | null;
    month: number | null;
    year: number | null;
  }
  
  export interface Broadcast {
    day: null | string;
    time: null | string;
    timezone: null | string;
    string: string;
  }
  
  export interface Genre {
    mal_id: number;
    type: Type;
    name: string;
    url: string;
  }
  
  export enum Type {
    Anime = 'anime',
  }
  
  export interface Image {
    image_url: string;
    small_image_url: string;
    large_image_url: string;
  }
  
  export interface Title {
    type: string;
    title: string;
  }
  
  export interface Trailer {
    youtube_id: string;
    url: string;
    embed_url: string;
    images: Images;
  }
  
  export interface Images {
    image_url: string;
    small_image_url: string;
    medium_image_url: string;
    large_image_url: string;
    maximum_image_url: string;
  }
  
  export interface Pagination {
    last_visible_page: number;
    has_next_page: boolean;
    current_page: number;
    items: Items;
  }
  
  export interface Items {
    count: number;
    total: number;
    per_page: number;
  }
  